### ISSUE TITLE
Value set links are 404 and Absolute in Reference Model Browser

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#24]
They are all broken.  It's us-breastcancer, not us/breastcancer.

Moreover, should these be changed to relative links? They seem to be absolute (rooted at hl7.org). That will break when the IG is finally deployed. WE SHOULD NOT HAVE ANY ABSOLUTE LINKS (unless they go outside the IG).

This is an example of a bad link:  http://hl7.org/fhir/us/breastcancer/ValueSet/cimi-statement-DiagnosticServiceVS

Needs to be changed to:  http://build.fhir.org/ig/HL7/us-breastcancer/ValueSet-cimi-statement-DiagnosticServiceVS.html

**Comment by cmoesel** [comment]
My understanding is that the IG will be deployed to http://hl7.org/fhir/us/breastcancer, and that redirects will be there as well, so in theory those links will be OK when the IG gets deployed for the ballot.  These are the canonical urls for the value sets, so we can’t change what they are (although we could change the underlying href target).
 
That said, it does make sense to have the links’ href targets go to the VS via a relative link, if the VS is defined in this IG.  This will ensure that the model-doc always points to the exact VS definitions that were defined at the same time as the content in the model-doc.  Otherwise, future versions will be locked into the value sets that were balloted (since they will be the ones at the absolute hl7.org links).
 
There are some challenges, however, since the model-doc was designed to be able to be used outside of the context of a FHIR IG.  It doesn’t know that those links should be treated as external – because they’re not in the model-doc’s scope (technically, they are external to the model-doc).  To support this, we’re going to have to add a special config parameter to tell the model-doc it is in an IG and to rewrite all those links.  It will also need to make certain assumptions about the way the IG looks and where it is deployed in the context of the IG.
 
Are you still wanting ADL too?  If so, I should probably take this task and let Abhijay continue on ADL.  If it’s getting too late to take on the risk of adding ADL in the mix, then I think Abhijay could run this task to ground.

**Comment by Abhijay** [comment]
Re-opening an auto-closed commit.

Will close when build is on build.fhir.org and verified

**Comment by cmoesel** [comment]
Confirmed working on build.fhir.org.
