### ISSUE TITLE
Logical Model: Why is Topic expanded but Context is not?

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#29]
Example: http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-oncology-BreastCancerHistologicGrade-model.html

evaluationResultTopic is a backbone element
recorded context is not

Is there a reason for this?

**Comment by cmoesel** [comment]
Element fields are expanded when the logical model applies nested constraints on them.  In this case, `BreastCancerHistologicGrade` applies many constraints on `evaluationResultTopic`.
See: https://github.com/standardhealth/shr_spec/blob/may-2018-ballot-topic-context/spec/oncology.txt#L119-L130

If any of the nested constraints of a field change a type (`is type` or `includes type`) then the field must be converted to a `BackboneElement` or a _section header_ (no specified `type`) -- this is because we don't have true inheritance, so changing a sub-type makes the parent type invalid.  So... this is why `evaluationResultTopic` is a `BackboneElement`.

`BreastCancerHistologicGrade` does _not_ apply any nested constraints on `recordedContext`.  This means the definition of `recordedContext` is _unmodified_.  Therefore there is no need to expand out its fields.

**Comment by cmoesel** [comment]
@markkramerus -- if you're happy w/ this explanation, please close this issue.  If you want further discussion, or if you'd like it to work a different way (for example, _always_ expanding field elements), please let me know.
