### ISSUE TITLE
Logical Model should use Coding instead of CodeableConcept

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/ballot#3]
Our logical models appear more complex than they could be because we are using the FHIR datatypes for coded values in the logical model. If we used something like "Concept" (a new datatype just for the logical models) that didn't have as much structure and did not require slicing, it would be easier to read the logical models.
The example shown below is from the 3-19-2018 version of the IG, for BreastCancer (condition) logical model, for the category attribute. It's just hard to see that the category is "disease". 

![capture3](https://user-images.githubusercontent.com/492232/37601921-9e2eb322-2b61-11e8-9f98-0ef396e6b76e.JPG)

**Comment by cmoesel** [comment]
Perhaps I'm not understanding you, but I don't see how we can use a "Concept" element "just for logical models" -- since the same CIMPL is used for profile and logical models.

Are you referring to the previous discussion of replacing all `Coding`/`CodeableConcept` in SHR w/ a single `Concept` element that knows how to map into those?

**Comment by markkramerus** [comment]
See if there is a way to replace CodeableConcept with Coding everywhere CodeableConcept is used in a logical model. We never need CodeableConcept in a logical model.

**Comment by markkramerus** [comment]
Looks like this is done in the last version of the logical models. Should I close it?
