### ISSUE TITLE
Child elements with zeroed out inherited fields aren't clear which field is being zeroed out

### ISSUE THREAD

**Issue by okeefm** [standardhealth/ballot#5]
When you have an element that inherits from another (such as `BreastSite` inheriting from `AnatomicalLocation`), and the child element zeroes out a field from the parent so it can't be set (such as `0..0 Directionality`), the resulting IG Table can miss important info (such as the name of the zeroed out field)

Example screenshot:
<img width="871" alt="screen shot 2018-03-19 at 2 43 11 pm" src="https://user-images.githubusercontent.com/49001/37616306-df87cc90-2b85-11e8-9d89-404e21bca84c.png">

the crossed out `qualifier` is the `0..0 Directionality` that's set on the child element.

IG link: https://cdn.rawgit.com/standardhealth/ballot/expanded/site/StructureDefinition-oncology-BreastSite.html

What I'd expect to see: either the name/ of the slice (`Directionality`) in the description, or that slice omitted from the profile entirely.

**Comment by cmoesel** [comment]
I've looked into this and confirmed that in the profile, we do provide the [short](StructureDefinition-oncology-BreastSite.html) description (e.g., "Directionality") that we'd expect in the _Descriptions & Constraints_ column (as well as the [binding](https://github.com/standardhealth/ballot/blob/expanded/site/StructureDefinition-oncology-BreastSite.json#L597-L602) to a directionality VS).

Since we provide it in the profile, it must be the IG publisher that is suppressing the information.  This may be intentional since the element is zeroed out.

Given that it's a slice, and we don't want it to exist, we may actually want to have the profile not mention it at all (rather than zeroing it out).  Since it's not inherited from anything, it probably doesn't make sense to zero it out.  Instead, we shouldn't put it in the StructureDefinition at all.

@markkramerus -- what do you think?

**Comment by okeefm** [comment]
An interesting note: that zeroed out slice doesn't appear on the `Snapshot Table` or the `All` table, just the Differential one

**Comment by cmoesel** [comment]
Yeah -- it's actually represented the _same_ in the snapshot and differential of the actual profile -- so that difference in display is purely a result of the IG publisher.

**Comment by cmoesel** [comment]
Fixed.
