### ISSUE TITLE
(Slightly) wrong display text for SCT#126926005

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/ballot#51]
We currently have this:
```
EntryElement:	BreastCancerPresenceStatement
Concept:		SCT#126926005 "Neoplasm of breast"
// some lines snipped because they're irrelevant to this issue
	ConditionTopic.TopicCode is SCT#126926005 "Neoplasm of breast"
```

This results in an IG Publisher warning:
![image](https://user-images.githubusercontent.com/2278253/38061725-80d954ee-32be-11e8-8a19-967287ab56a6.png)

It turns out the publisher is really picky.  We have `Neoplasm of breast` but it wants `Neoplasm of breast (disorder)`.

If we fix it to this, the publisher is happy:
```
EntryElement:	BreastCancerPresenceStatement
Concept:		SCT#126926005 "Neoplasm of breast (disorder)"
// some lines snipped because they're irrelevant to this issue
	ConditionTopic.TopicCode is SCT#126926005 "Neoplasm of breast (disorder)"
```

**Comment by rutemartins** [comment]
It seems like we have to use the fully specified name for the SNOMED-CT code, which makes sense. The resolution will be a bit different though, since the code is incorrect: a neoplasm of the breast can be a benign tumor, so I will replace with a more appropriate code and make sure to include the fully specified description.

**Comment by markkramerus** [comment]
Not sure about this. We have some input that the condition might be reported before it is fully characterized. It might be determined to be malignant sometime after it has been detected.

**Comment by cmoesel** [comment]
Deployed
