### ISSUE TITLE
HistologicGrade should have a reference to the histologic type in the BreastCancer profile.

### ISSUE THREAD

**Issue by mayterry88** [standardhealth/ballot#7]
There could be multiple histologic types with varying histologic grades for a cancer type.  Without a reference, there would be no clear association to the specific histologic type associated BreastCancer and could in turn affect the overall stage calculation.

**Comment by markkramerus** [comment]
I think we are ok with this because we can navigate from the cancer condition to its staging and thence to the histologic grade. The cancer condition has the histologic type. If it proves useful to ALSO have the histologic type in the histologic grade, we could include that element, but it would be a copy of information available elsewhere.
